name = "cfcontactform1"
main = "worker.js"
compatibility_date = "2024-01-01"

# Define variables that users will need to configure
[vars]
DOMAIN_NAME = "example.com"  # REPLACE WITH YOUR DOMAIN

# Secrets (use wrangler secret put commands):
# - mailgunApiKey
# - mailgunDomain  
# - cloudflareEmail
# - senderEmail